events { worker_connections 1024; }

http {
    include /etc/nginx/mime.types;

    upstream backend {
        server backend:5010;   # UUSI backend-portti
    }

    server {
        listen 80;
        server_name localhost;

        # STATIC FRONTEND
        location /kube/ {
            alias /usr/share/nginx/html/;
            index index.html;
            try_files $uri $uri/ /kube/index.html;
        }

        # API ROUTES
        location /kube/api/ {
            proxy_pass http://backend/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
